# diabetes detection project
- diabetes dataset
- svm classifier

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

# Preprocessing

## Chargement des donnes

In [2]:
data = pd.read_csv('diabetes.csv')
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [3]:
data.shape

(768, 9)

In [4]:
data.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [5]:
data['Outcome'].value_counts()

0    500
1    268
Name: Outcome, dtype: int64

## 0 est le label des personnes non diabetiques
## 1 est le label des personnes diabetiques

In [6]:
features = data.drop(columns='Outcome',axis=1) # suppression de la colonne Outcome des autres colonne
label = data['Outcome'] # selection de la colonne Outcome parmis les autres colonne

In [7]:
features

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [8]:
label

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

## Standardisation des donnees

In [9]:
# Créez une instance de StandardScaler
scaler = StandardScaler()

# Ajustez le scaler aux données
scaler.fit(features)

StandardScaler()

In [10]:
# Transformez les données en utilisant le scaler
features_scaled = scaler.transform(features)

In [11]:
features_scaled

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [12]:
features = features_scaled

In [13]:
features

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

## Division des donnees en donnees d'entrainement et donnees test

In [14]:
# Divisez vos données en ensembles d'entraînement et de test
features_train, features_test, label_train, label_test = train_test_split(features, label, test_size=0.2)

In [15]:
features_train.shape

(614, 8)

In [16]:
features_test.shape

(154, 8)

# Entrainement du model

In [17]:
classifier = svm.SVC(kernel='linear')
classifier.fit(features_train,label_train)

SVC(kernel='linear')

# Evaluation du model

## precision avec les donnees tests 

In [18]:
label_train_prediction = classifier.predict(features_train)
accuracy_score(label_train_prediction,label_train)

0.7752442996742671

## precision avec les donnees tests

In [19]:
label_test_prediction = classifier.predict(features_test)
accuracy_score(label_test_prediction,label_test)

0.8116883116883117

# Test du model en production

Le model a deja ete entraine et teste. il est possible d'utiliser des techniques d'optimisation pour augmenter la precision actuelle. Pour l'instant nous allons supposer que en production le systeme recoit la donnes suivante et voyons comment il reagit

In [20]:
input_sample = (5,166,72,19,175,22.7,0.6,51)
input_sample_1 = (6,148,72,35,0,33.6,0.627,50)
input_sample_0 = (1,85,66,29,0,175.6,0.351,31)
input_np_array = np.asarray(input_sample_0)
input_np_array_reshape = input_np_array.reshape(1,-1)

In [21]:
input_np_array

array([  1.   ,  85.   ,  66.   ,  29.   ,   0.   , 175.6  ,   0.351,
        31.   ])

In [22]:
input_np_array_reshape.shape

(1, 8)

In [23]:
std_data = scaler.transform(input_np_array_reshape)
std_data

/home/benjojo/.local/lib/python3.8/site-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[-0.84488505, -1.12339636, -0.16054575,  0.53090156, -0.69289057,
        18.22654561, -0.36506078, -0.19067191]])

In [24]:
prediction = classifier.predict(std_data)
prediction

array([1])

In [25]:
if(prediction[0]==0):
    print("the person is not diabetic")
else :
    print("the person is diabetic")

the person is diabetic
